---
virtualmachines:
  - name: "rhel"
    image: "rhel-9-5-1-17-25"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
