---
virtualmachines:
  - name: "bastion"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
  - name: "satellite"
    image: "satellite-dv"
    bootloader: efi
    memory: "32G"
    cores: 1
    image_size: "540G"
    packages:
      - git
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: satellite
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: webui
    routes:
      - name: satellite
        host: satellite
        service: satellite
        targetPort: 443
        tls: true
        tls_termination: passthrough
  - name: "rhel2"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
